spring:
  application:
    name: rag
  ai:
    # openai:
    #   moderation:
    #     options:
    #       model: google/gemma-3-12b
    #   base-url: http://localhost:1234
    #   api-key: your api key
    ollama:
      chat:
        model: llama3.2:latest
      init:
        pull-model-strategy: WHEN_MISSING
        timeout: 10m
    vectorstore:
      pgvector:
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: testuser
    password: testpwd