spring:
  application:
    name: rag
  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop
      stop:
        command: down
        timeout: 5s
  ai:
    # openai:
    #   moderation:
    #     options:
    #       model: google/gemma-3-12b
    #   base-url: http://localhost:1234
    #   api-key: your api key
    ollama:
      chat:
        model: llama3.2:latest
      init:
        pull-model-strategy: WHEN_MISSING
        timeout: 10m
    openai:
      embedding:
        options:
          model: nomic-ai/text-embedding-nomic-embed-text-v1.5
      moderation:
        options:
          model: google/gemma-3-12b
      base-url: http://localhost:1234
      api-key: test
    vectorstore:
      pgvector:
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: testuser
    password: testpwd